# Generated by Django 6.0.7 on 2026-07-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=100)),
                ('child_name', models.CharField(max_length=100)),
                ('child_age', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_centre', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('assigned_owner', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Demo Scheduled', 'Demo Scheduled'), ('Demo Completed', 'Demo Completed'), ('Converted', 'Converted'), ('Lost', 'Lost')], default='New', max_length=20)),
                ('next_followup', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
